import assert from "node:assert/strict"; import {mkdtempSync,rmSync} from "node:fs"; import {tmpdir} from "node:os"; import {join} from "node:path"; import {BusinessManager} from "../src/business/manager.js";
const dir=mkdtempSync(join(tmpdir(),"layanx-business-")); process.env.LAYANX_BUSINESS_STORAGE_PATH=join(dir,"business.json");
const b=new BusinessManager();
const store=b.createStore({name:"Demo",platform:"generic",baseUrl:"https://example.invalid",enabled:true});
const product=b.createProduct({storeId:store.id,sku:"SKU-1",name:"Hojari Frankincense",description:"Natural product",price:5,currency:"OMR",inventory:10,images:["https://cdn.example/item.jpg"],videos:[],tags:["لبان","حوجري"]});
const content=b.generateProductContent(product.id);
assert.equal(content.status,"draft"); assert.equal(content.mediaIds.length,0);
const media=b.addMedia({kind:"image",url:"https://cdn.example/item.jpg",metadata:{}});
const content2=b.generateProductContent(product.id); assert.equal(content2.mediaIds.length,1);
b.updateContent(content2.id,{status:"approved"}); assert.equal(b.snapshot().content.find(c=>c.id===content2.id)?.status,"approved");
const restored=new BusinessManager(); assert.equal(restored.snapshot().products.length,1); assert.equal(restored.snapshot().stores.length,1);
rmSync(dir,{recursive:true,force:true}); console.log("business manager integration: ok");
