import {LayanXCore} from "../src/core/orchestrator.js";
import {CoreRuntime} from "../src/core/core-runtime.js";
const core=new LayanXCore();
core.registerAgent({agentId:"integration",purpose:"integration",allowedTools:["echo"],forbiddenResources:["secrets"],requiredPermission:"L1_READ",maxToolCalls:5,maxRuntimeMs:10000,successCriteria:["echo"],stopCondition:"stop"});
core.tools.register({name:"echo",description:"echo",permission:"L1_READ",dangerous:false});
const runtime=new CoreRuntime(core);
const result=await runtime.run("Integration mission",{agentId:"integration",tool:"echo",action:"echo",permission:"L1_READ",idempotencyKey:crypto.randomUUID(),payload:"integration-ok"},{execute:async r=>r.payload});
if(!result.ok||!result.verified)throw new Error("Full integration flow failed");
if(core.audit.list().length<2)throw new Error("Audit trail missing");
if(!core.executionStates.get(result.missionId))throw new Error("Execution state missing");
console.log("Full integration flow test passed.");
