import {startRuntimeApi} from "../src/api-server.js";
import {LayanXCore} from "../src/core/orchestrator.js";
import type {ModelProviderAdapter} from "../src/models/inference.js";
const core=new LayanXCore();
core.registerAgent({agentId:"core",purpose:"test",allowedTools:[],forbiddenResources:["secrets"],requiredPermission:"L1_READ",maxToolCalls:10,maxRuntimeMs:1000,successCriteria:["done"],stopCondition:"stop"});
const provider:ModelProviderAdapter={name:"test",async health(){return{provider:"test",available:true,updatedAt:new Date().toISOString()};},async generate(model){return{provider:"test",modelId:model.id,output:JSON.stringify({risk:"low",requiredPermission:"L1_READ",steps:[{description:"plan"}],successCriteria:["done"],stopCondition:"stop"})};}};
core.models.register({id:"test-model",provider:"test",capabilities:["reasoning"],local:true,enabled:true,priority:1});core.providers.register(provider);
const server=startRuntimeApi({core,host:"127.0.0.1",port:0});
await new Promise<void>(resolve=>server.on("listening",resolve));
const address=server.address();if(!address||typeof address==="string")throw new Error("bind failed");const base="http://127.0.0.1:"+address.port;
const created=await fetch(base+"/v1/missions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal:"inspect runtime"})});if(created.status!==201)throw new Error("create failed");
const payload=await created.json() as {mission:{id:string}};
const one=await fetch(base+"/v1/missions/"+payload.mission.id);if(!one.ok)throw new Error("mission detail failed");
const detail=await one.json() as {mission:{id:string};audit:unknown[];ledger:unknown[]};if(detail.mission.id!==payload.mission.id||detail.audit.length===0||detail.ledger.length===0)throw new Error("mission detail incomplete");
const list=await fetch(base+"/v1/missions");if(!list.ok)throw new Error("mission list failed");
const listPayload=await list.json() as {missions:Array<{id:string}>};if(!listPayload.missions.some(item=>item.id===payload.mission.id))throw new Error("mission missing from list");
server.close();console.log("Mission lifecycle API test passed.");
