import assert from "node:assert/strict";
import {mkdtempSync,writeFileSync,rmSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {NativeSocialConnector} from "../src/business/native-social.js";
process.env.LAYANX_TIKTOK_SOCIAL_TOKEN="test-token";process.env.LAYANX_YOUTUBE_SOCIAL_TOKEN="yt-token";
const dir=mkdtempSync(join(tmpdir(),"layanx-social-local-"));const file=join(dir,"video.mp4");writeFileSync(file,Buffer.alloc(1024,1));const original=globalThis.fetch;
let tiktokCalls=0;globalThis.fetch=(async(url,init)=>{tiktokCalls++;if(String(url).includes("creator_info"))return new Response(JSON.stringify({data:{privacy_level_options:["SELF_ONLY"]}}),{status:200});if(String(url).includes("/video/init"))return new Response(JSON.stringify({data:{publish_id:"pub1",upload_url:"https://upload.test/u"}}),{status:200});if(String(url)==="https://upload.test/u")return new Response("",{status:201});throw new Error("unexpected");}) as typeof fetch;
const tt=await new NativeSocialConnector("tiktok").publish({id:"t",platform:"tiktok",name:"t",enabled:true,createdAt:new Date().toISOString()},{title:"Quran",body:"credit",mediaUrls:[file]});assert.equal(tt.externalId,"pub1");assert.equal(tiktokCalls,3);
globalThis.fetch=(async(url)=>{assert.equal(String(url),"https://www.googleapis.com/upload/youtube/v3/videos?uploadType=multipart&part=snippet,status");return new Response(JSON.stringify({id:"yt1"}),{status:200});}) as typeof fetch;
const yt=await new NativeSocialConnector("youtube").publish({id:"y",platform:"youtube",name:"y",enabled:true,createdAt:new Date().toISOString()},{title:"Quran",body:"credit",mediaUrls:[file]});assert.equal(yt.externalId,"yt1");
globalThis.fetch=original;rmSync(dir,{recursive:true,force:true});console.log("native local video: ok");