import {LayanXCore} from "../src/core/orchestrator.js";
import {ExecutionRuntime} from "../src/core/runtime.js";
const core=new LayanXCore();
core.registerAgent({agentId:"recovery-test",purpose:"test",allowedTools:["unstable"],forbiddenResources:["secrets"],requiredPermission:"L1_READ",maxToolCalls:3,maxRuntimeMs:10000,successCriteria:["valid steps"],stopCondition:"stop"});
core.tools.register({name:"unstable",description:"test",permission:"L1_READ",dangerous:false});
const mission=core.startMission("Recovery test");
const runtime=new ExecutionRuntime(core);
let attempts=0;
const result=await runtime.run(mission,{missionId:mission.id,agentId:"recovery-test",tool:"unstable",action:"unstable",permission:"L1_READ",idempotencyKey:crypto.randomUUID(),payload:"x"},{execute:async()=>{attempts++;if(attempts===1)throw new Error("transient");return"recovered";}});
if(result.ok)throw new Error("Direct runtime should expose transient failure.");
if(!core.recovery.restore(mission.id))throw new Error("Checkpoint was not created.");
console.log("Recovery checkpoint test passed.");
