import assert from "node:assert/strict";
import {createServer} from "node:http";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {BusinessManager} from "../src/business/manager.js";
import {socialIdempotencyKey} from "../src/business/connectors.js";

const dir=mkdtempSync(join(tmpdir(),"layanx-social-recovery-"));
process.env.LAYANX_BUSINESS_STORAGE_PATH=join(dir,"business.json");
const server=createServer((req,res)=>{res.setHeader("content-type","application/json");res.end(JSON.stringify({id:"post-1",url:"https://example.test/post-1"}));});
await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));
const port=(server.address() as any).port;
process.env.LAYANX_INSTAGRAM_SOCIAL_TOKEN="recovery-test";
process.env.LAYANX_INSTAGRAM_SOCIAL_PUBLISH_URL=`http://127.0.0.1:${port}/publish`;
delete process.env.LAYANX_FACEBOOK_SOCIAL_PUBLISH_URL;
const b=new BusinessManager();
const store=b.createStore({name:"Demo",platform:"generic",baseUrl:"https://example.invalid",enabled:true});
const product=b.createProduct({storeId:store.id,sku:"SKU",name:"Product",description:"Description",price:1,currency:"OMR",inventory:1,images:[],videos:[],tags:[]});
b.upsertSocialAccount({platform:"instagram",name:"IG",externalId:"ig",enabled:true});
b.upsertSocialAccount({platform:"facebook",name:"FB",externalId:"fb",enabled:true});
const content=b.createContent({title:"T",body:"B",platforms:["instagram","facebook"],mediaIds:[],status:"approved"});
const first=await b.publishContent(content.id) as any;
assert.notEqual(socialIdempotencyKey({id:"a",platform:"instagram",name:"A",enabled:true,createdAt:"now"},{title:"T",body:"B",mediaUrls:["https://a.test/1.jpg"]}),socialIdempotencyKey({id:"a",platform:"instagram",name:"A",enabled:true,createdAt:"now"},{title:"T",body:"B",mediaUrls:["https://a.test/2.jpg"]}));
assert.equal(first.results.length,1);
assert.equal(first.failures.length,1);
assert.equal(b.snapshot().content[0]?.status,"scheduled");
assert.equal(b.snapshot().content[0]?.publicationResults?.length,1);
const second=await b.publishContent(content.id) as any;
assert.equal(second.results.length,0);
assert.equal(second.failures.length,1);
assert.equal(b.snapshot().content[0]?.publicationResults?.length,1);
await new Promise<void>(resolve=>server.close(()=>resolve()));
rmSync(dir,{recursive:true,force:true});
console.log("social publication recovery: ok");
