import {mkdtemp,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {JsonStateStore} from "../src/core/persistence.js";
import {JsonRepository} from "../src/storage/json-repository.js";
import {JsonStorageAdapter} from "../src/storage/json-adapter.js";
const dir=await mkdtemp(join(tmpdir(),"layanx-storage-"));
const repo=new JsonRepository(new JsonStorageAdapter(join(dir,"items.json")),"items");
await repo.upsert({id:"1",value:"ok"});
if((await repo.get("1"))?.value!=="ok")throw new Error("Repository read failed.");
await repo.remove("1");
if(await repo.get("1"))throw new Error("Repository delete failed.");
await rm(dir,{recursive:true,force:true});
console.log("Storage abstraction test passed.");
