import {createServer,IncomingMessage,ServerResponse} from "node:http";
import {FlowRuntime} from "./runtime.js";
import type {FlowDefinition,FlowEvent} from "./types.js";
import type {LayanXCore} from "../core/orchestrator.js";
const json=(r:ServerResponse,s:number,b:unknown)=>{r.statusCode=s;r.setHeader("content-type","application/json; charset=utf-8");r.end(JSON.stringify(b));};
async function body(req:IncomingMessage,max=262144){let n=0;const a:Buffer[]=[];for await(const c of req){const b=Buffer.isBuffer(c)?c:Buffer.from(c);n+=b.length;if(n>max)throw new Error("request_too_large");a.push(b);}const raw=Buffer.concat(a).toString("utf8");if(!raw)return{};return JSON.parse(raw) as Record<string,unknown>;}
const page=()=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LayanX Flow Builder</title><style>body{margin:0;font-family:system-ui;background:#0b1020;color:#e8ecf5}header{padding:16px 22px;background:#11182c;display:flex;gap:18px;align-items:center}main{display:grid;grid-template-columns:260px 1fr 300px;height:calc(100vh - 65px)}aside{padding:16px;background:#0f172a;border-right:1px solid #24304a}#canvas{position:relative;overflow:auto;background:radial-gradient(circle,#17213a 1px,transparent 1px);background-size:24px 24px}.node{position:absolute;width:190px;padding:12px;border:1px solid #33466f;border-radius:12px;background:#151f36;cursor:pointer;box-shadow:0 8px 22px #0006}.node b{display:block;margin-bottom:5px}.node small{color:#9fb0cf}.palette button,header button{width:100%;margin:5px 0;padding:9px;border:0;border-radius:8px;background:#243454;color:#fff;cursor:pointer}.panel{padding:16px;background:#0f172a;border-left:1px solid #24304a}.panel input,.panel textarea,.panel select{width:100%;box-sizing:border-box;margin:6px 0 12px;padding:9px;background:#111827;border:1px solid #33466f;color:#fff;border-radius:7px}pre{white-space:pre-wrap;font-size:12px;color:#b9c7df}</style></head><body><header><strong>🤖 LayanX Flow Builder</strong><span id="status">local-first</span><input id="token" placeholder="API token (optional)" style="max-width:220px;background:#111827;color:#fff;border:1px solid #33466f;padding:8px;border-radius:7px"><button style="width:auto;margin-left:auto" onclick="save()">Save & Activate</button></header><main><aside><h3>Blocks</h3><div class="palette" id="palette"></div><h3>Flows</h3><select id="flows" onchange="loadFlow(this.value)"></select><button onclick="newFlow()">New Flow</button><button onclick="runTest()">Test with Message</button></aside><section id="canvas"></section><section class="panel"><h3>Selected Node</h3><div id="editor">Select a node.</div><h3>Flow JSON</h3><pre id="json"></pre></section></main><script>
let flow={id:crypto.randomUUID(),projectId:'default',name:'New Flow',status:'draft',version:1,nodes:[],edges:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},selected=null;
const types=[['trigger','Trigger'],['ai_agent','AI Agent'],['condition','Condition'],['tool','Tool / Action'],['message','Message'],['crm_upsert','CRM'],['handoff','Human Agent'],['end','End']];
function draw(){canvas.innerHTML='';for(const n of flow.nodes){const d=document.createElement('div');d.className='node';d.style.left=(n.position?.x??40)+'px';d.style.top=(n.position?.y??40)+'px';d.innerHTML='<b>'+n.label+'</b><small>'+n.type+'</small>';d.onclick=()=>select(n.id);canvas.appendChild(d)}json.textContent=JSON.stringify(flow,null,2)}
function select(id){selected=flow.nodes.find(n=>n.id===id);if(!selected)return;editor.innerHTML='<label>Label</label><input id="lab" value="'+(selected.label??'')+'"><label>Config JSON</label><textarea id="cfg" rows="12">'+JSON.stringify(selected.config,null,2)+'</textarea><button onclick="applyNode()">Apply</button><button onclick="removeNode()">Delete</button>'}
function applyNode(){try{selected.label=document.getElementById('lab').value;selected.config=JSON.parse(document.getElementById('cfg').value||'{}');flow.updatedAt=new Date().toISOString();draw();select(selected.id)}catch(e){alert(e.message)}}
function removeNode(){const id=selected.id;flow.nodes=flow.nodes.filter(n=>n.id!==id);flow.edges=flow.edges.filter(e=>e.source!==id&&e.target!==id);selected=null;editor.textContent='Select a node.';draw()}
function add(type){const previous=selected?.id??flow.nodes.at(-1)?.id;const n={id:crypto.randomUUID(),type,label:types.find(x=>x[0]===type)?.[1]??type,config:{},position:{x:60+flow.nodes.length%3*220,y:60+Math.floor(flow.nodes.length/3)*130}};if(type==='trigger')n.config={eventType:'message'};if(type==='ai_agent')n.config={goal:'Reply to {{event.text}}',sendResponse:true};if(type==='condition')n.config={expression:'event.text contains buy'};if(type==='message')n.config={text:'{{event.text}}'};flow.nodes.push(n);if(previous)flow.edges.push({id:crypto.randomUUID(),source:previous,target:n.id});selected=n;draw();select(n.id)}
function newFlow(){flow={id:crypto.randomUUID(),projectId:'default',name:'New Flow',status:'draft',version:1,nodes:[],edges:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};selected=null;draw()}

async function save(){flow.status='active';flow.version++;flow.updatedAt=new Date().toISOString();const r=await api('/v1/flows',{method:'POST',body:JSON.stringify(flow)});alert(r.ok?'Saved':'Save failed: '+JSON.stringify(r));await list()}
async function list(){const r=await api('/v1/flows?projectId='+encodeURIComponent(flow.projectId));document.getElementById('flows').innerHTML=(r.flows||[]).map(x=>'<option value="'+x.id+'">'+x.name+'</option>').join('');}
async function loadFlow(id){if(!id)return;const r=await api('/v1/flows/'+encodeURIComponent(id));if(r.flow){flow=r.flow;draw()}}
async function runTest(){const text=prompt('Message','I want to buy this product');if(text===null)return;const r=await api('/v1/flows/inbound',{method:'POST',body:JSON.stringify({projectId:flow.projectId,channel:'webchat',senderId:'test-user',chatId:'test-chat',text})});alert(JSON.stringify(r,null,2))}
async function api(path,opt={}){const headers=Object.assign({'content-type':'application/json'},opt.headers||{});const token=document.getElementById('token').value.trim()||localStorage.getItem('layanxToken')||'';if(token){headers.authorization='Bearer '+token;localStorage.setItem('layanxToken',token)}const r=await fetch(path,Object.assign({},opt,{headers}));return r.json()}
types.forEach(([t,l])=>{const b=document.createElement('button');b.textContent=l;b.onclick=()=>add(t);palette.appendChild(b)});draw();list();
</script></body></html>`;
export function startFlowServer(core:LayanXCore,options:{host?:string;port?:number;token?:string;runtime?:FlowRuntime}={}){const runtime=options.runtime??new FlowRuntime(core);const host=options.host??process.env.LAYANX_FLOW_HOST??"127.0.0.1";const port=options.port??Number(process.env.LAYANX_FLOW_PORT??3100);const token=options.token??process.env.LAYANX_API_TOKEN;const authorized=(req:IncomingMessage)=>!token||req.headers.authorization==="Bearer "+token;
 const server=createServer(async(req,res)=>{const url=new URL(req.url??"/","http://localhost");if(req.method==="GET"&&url.pathname==="/"){res.statusCode=302;res.setHeader("location","/flow");res.end();return}if(req.method==="GET"&&url.pathname==="/flow"){res.statusCode=200;res.setHeader("content-type","text/html; charset=utf-8");res.end(page());return}if(!authorized(req)){json(res,401,{ok:false,error:"unauthorized"});return}
 try{
  if(req.method==="GET"&&url.pathname==="/v1/flows"){json(res,200,{ok:true,flows:await runtime.getStore().listFlows(url.searchParams.get("projectId")??undefined)});return}
  if(req.method==="GET"&&url.pathname==="/v1/flows/executions"){const flow=await runtime.getStore().getFlow(decodeURIComponent(url.pathname.split("/")[3]??""));if(!flow){json(res,404,{ok:false,error:"flow_not_found"});return}json(res,200,{ok:true,flow});return}
  if(req.method==="POST"&&url.pathname==="/v1/flows"){const input=await body(req);const flow=input as unknown as FlowDefinition;runtime.validate(flow);await runtime.getStore().saveFlow(flow);json(res,201,{ok:true,flow});return}
  if(req.method==="DELETE"&&url.pathname.startsWith("/v1/flows/")){await runtime.getStore().deleteFlow(decodeURIComponent(url.pathname.split("/")[3]??""));json(res,200,{ok:true});return}
  if(req.method==="GET"&&url.pathname==="/v1/flows/executions"){json(res,200,{ok:true,executions:await runtime.getStore().listExecutions(url.searchParams.get("projectId")??undefined)});return}
  if(req.method==="POST"&&url.pathname==="/v1/flows/inbound"){const input=await body(req);const required=["projectId","channel","senderId","chatId","text"];if(required.some(k=>typeof input[k]!=="string"||!(input[k] as string).trim())){json(res,400,{ok:false,error:"projectId, channel, senderId, chatId, and text are required"});return}const flows=await runtime.getStore().listFlows(input.projectId as string);const event:FlowEvent={id:crypto.randomUUID(),projectId:input.projectId as string,channel:input.channel as string,senderId:input.senderId as string,chatId:input.chatId as string,text:input.text as string,timestamp:new Date().toISOString(),metadata:input.metadata as Record<string,unknown>|undefined};const triggerType=typeof input.eventType==="string"?input.eventType:"message";const candidates=flows.filter(f=>f.status==="active"&&f.nodes.some(n=>n.type==="trigger"&&(n.config.eventType===triggerType||n.config.eventType==="*")));const results=[];for(const flow of candidates)results.push(await runtime.execute(flow,event));json(res,200,{ok:true,matched:candidates.length,results});return}
  json(res,404,{ok:false,error:"not_found"});
 }catch(error){json(res,422,{ok:false,error:error instanceof Error?error.message:"flow_server_error"});}
 });server.listen(port,host);return server;}
