import {randomUUID} from "node:crypto";
import type {BusinessSnapshot,AdPlatform,AdStatus,AdAccount,PaidCampaign,AdGroup,AdCreative,PaidAd,AdMetric} from "./types.js";
import {BusinessStore} from "./store.js";
import {configuredAdsConnector} from "./ad-connectors.js";

export const emptyAds=():AdsSnapshot=>({adAccounts:[],paidCampaigns:[],adGroups:[],adCreatives:[],paidAds:[],adMetrics:[]});
export class AdsManager{
 constructor(private readonly store:BusinessStore){}
 snapshot():AdsSnapshot{const s=this.store.snapshot();return {adAccounts:s.adAccounts??[],paidCampaigns:s.paidCampaigns??[],adGroups:s.adGroups??[],adCreatives:s.adCreatives??[],paidAds:s.paidAds??[],adMetrics:s.adMetrics??[]};}
 private mutate(fn:(s:BusinessSnapshot)=>void){return this.store.mutate(fn);}
 addAccount(input:Omit<AdAccount,"id"|"createdAt">){const s=this.snapshot();const existing=s.adAccounts.find(a=>a.platform===input.platform&&a.accountId===input.accountId);if(existing)return existing;const a={...input,id:randomUUID(),createdAt:new Date().toISOString()};this.mutate(s=>{s.adAccounts??=[];s.adAccounts.push(a)});return a;}
 createCampaign(input:Omit<PaidCampaign,"id"|"createdAt"|"updatedAt">){if(!this.snapshot().adAccounts.some(a=>a.id===input.accountId))throw new Error("ad_account_not_found");const c={...input,id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.mutate(s=>{s.paidCampaigns??=[];s.paidCampaigns.push(c)});return c;}
 createAdGroup(input:Omit<AdGroup,"id"|"createdAt"|"updatedAt">){if(!this.snapshot().paidCampaigns.some(c=>c.id===input.campaignId))throw new Error("paid_campaign_not_found");const g={...input,id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.mutate(s=>{s.adGroups??=[];s.adGroups.push(g)});return g;}
 createCreative(input:Omit<AdCreative,"id"|"createdAt"|"updatedAt">){const c={...input,id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.mutate(s=>{s.adCreatives??=[];s.adCreatives.push(c)});return c;}
 createAd(input:Omit<PaidAd,"id"|"createdAt"|"updatedAt">){const s=this.snapshot();if(!s.adGroups.some(g=>g.id===input.adGroupId))throw new Error("ad_group_not_found");if(!s.adCreatives.some(c=>c.id===input.creativeId))throw new Error("creative_not_found");const a={...input,id:randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.mutate(s=>{s.paidAds??=[];s.paidAds.push(a)});return a;}
 recordMetric(input:Omit<AdMetric,"id"|"createdAt">){const m={...input,id:randomUUID(),createdAt:new Date().toISOString()};this.mutate(s=>{s.adMetrics??=[];const i=s.adMetrics.findIndex(x=>x.platform===m.platform&&x.campaignId===m.campaignId&&x.date===m.date);if(i>=0)s.adMetrics[i]=m;else s.adMetrics.push(m)});return m;}
 async launchCampaign(campaignId:string){const s=this.snapshot(),c=s.paidCampaigns.find(x=>x.id===campaignId);if(!c)throw new Error("paid_campaign_not_found");const a=s.adAccounts.find(x=>x.id===c.accountId);if(!a||!a.enabled)throw new Error("ad_account_not_configured");const connector=configuredAdsConnector(a.platform);const result=c.externalId?await connector.updateCampaign(a,{...c,status:"active"}):await connector.createCampaign(a,{...c,status:"active"});const externalId=result?.externalId??result?.id??result?.campaignId??result?._headers?.["x-restli-id"];if(!externalId)throw new Error("ads_connector_missing_external_id");this.mutate(s=>{const item=s.paidCampaigns!.find(x=>x.id===campaignId)!;Object.assign(item,{status:"active",externalId:String(externalId),updatedAt:new Date().toISOString()})});return {campaign:this.snapshot().paidCampaigns.find(x=>x.id===campaignId),raw:result};}
 async pauseCampaign(campaignId:string){const s=this.snapshot(),c=s.paidCampaigns.find(x=>x.id===campaignId);if(!c)throw new Error("paid_campaign_not_found");const a=s.adAccounts.find(x=>x.id===c.accountId);if(!a||!a.enabled)throw new Error("ad_account_not_configured");if(c.externalId)await configuredAdsConnector(a.platform).pauseCampaign(a,c);this.mutate(s=>{const item=s.paidCampaigns!.find(x=>x.id===campaignId)!;item.status="paused";item.updatedAt=new Date().toISOString()});return this.snapshot().paidCampaigns.find(x=>x.id===campaignId)!;}
 async syncInsights(accountId:string,campaignId?:string){const s=this.snapshot(),a=s.adAccounts.find(x=>x.id===accountId);if(!a)throw new Error("ad_account_not_found");const c=campaignId?s.paidCampaigns.find(x=>x.id===campaignId):undefined;const metrics=await configuredAdsConnector(a.platform).insights(a,c);for(const m of metrics)this.recordMetric({...m,platform:a.platform,accountId:a.id,campaignId:m.campaignId??c?.id??"",currency:m.currency??a.currency});return metrics;}
 dashboard(){const s=this.snapshot();const spend=s.adMetrics.reduce((n,m)=>n+m.spend,0),revenue=s.adMetrics.reduce((n,m)=>n+m.revenue,0),clicks=s.adMetrics.reduce((n,m)=>n+m.clicks,0),impressions=s.adMetrics.reduce((n,m)=>n+m.impressions,0),conversions=s.adMetrics.reduce((n,m)=>n+m.conversions,0);return {accounts:s.adAccounts.length,campaigns:s.paidCampaigns.length,activeCampaigns:s.paidCampaigns.filter(c=>c.status==="active").length,adGroups:s.adGroups.length,ads:s.paidAds.length,impressions,clicks,conversions,spend,revenue,roas:spend?revenue/spend:0,ctr:impressions?clicks/impressions:0,cpa:conversions?spend/conversions:0};}
}