import {localSecret} from "../security/local-secret-vault.js";
import type {Product,Order,SocialAccount,SocialPlatform,Store} from "./types.js";
export interface ConnectorResult{externalId?:string;raw:unknown}
export interface CommerceConnector{platform:string;createProduct(store:Store,product:Product):Promise<ConnectorResult>;updateProduct(store:Store,product:Product):Promise<ConnectorResult>;listOrders(store:Store):Promise<Order[]>;}
export interface SocialConnector{platform:SocialPlatform;publish(account:SocialAccount,item:{title:string;body:string;mediaUrls:string[]}):Promise<{externalId:string;url?:string}>;}
async function request(url:string,init:RequestInit={}):Promise<any>{const r=await fetch(url,{...init,headers:{"content-type":"application/json",...(init.headers??{})}});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}};if(!r.ok)throw new Error(`connector_http_${r.status}`);return d;}
function productPayload(p:Product){return {name:p.name,sku:p.sku,description:p.description,price:String(p.price),currency:p.currency,inventory:p.inventory,images:p.images,tags:p.tags};}
export class GenericCommerceConnector implements CommerceConnector{
 platform="generic"; constructor(protected readonly token=localSecret("commerce.token",process.env.LAYANX_COMMERCE_TOKEN)){}
 protected headers():Record<string,string>{const h:Record<string,string>={};if(this.token)h.authorization=`Bearer ${this.token}`;return h;}
 async createProduct(store:Store,product:Product){const raw=await request(`${store.baseUrl.replace(/\/$/,"")}/products`,{method:"POST",headers:this.headers(),body:JSON.stringify(productPayload(product))});return {externalId:raw?.id?String(raw.id):undefined,raw};}
 async updateProduct(store:Store,product:Product){const raw=await request(`${store.baseUrl.replace(/\/$/,"")}/products/${encodeURIComponent(product.externalId??product.id)}`,{method:"PUT",headers:this.headers(),body:JSON.stringify(productPayload(product))});return {externalId:raw?.id?String(raw.id):product.externalId,raw};}
 async listOrders(store:Store){const d=await request(`${store.baseUrl.replace(/\/$/,"")}/orders`,{headers:this.headers()});return Array.isArray(d)?d:(d.orders??[]);}
}
export class ShopifyConnector extends GenericCommerceConnector{
 override platform="shopify";
 private shopHeaders():Record<string,string>{const token=localSecret("shopify.access_token",process.env.LAYANX_SHOPIFY_ACCESS_TOKEN);if(!token)throw new Error("LAYANX_SHOPIFY_ACCESS_TOKEN is required");return {"X-Shopify-Access-Token":token};}
 override async createProduct(store:Store,product:Product){const raw=await request(`${store.baseUrl.replace(/\/$/,"")}/products.json`,{method:"POST",headers:this.shopHeaders(),body:JSON.stringify({product:{title:product.name,body_html:product.description,tags:product.tags.join(","),variants:[{sku:product.sku,price:String(product.price),inventory_quantity:product.inventory}]}})});return {externalId:raw?.product?.id?String(raw.product.id):undefined,raw};}
 override async updateProduct(store:Store,product:Product){if(!product.externalId) return this.createProduct(store,product);const raw=await request(`${store.baseUrl.replace(/\/$/,"")}/products/${encodeURIComponent(product.externalId)}.json`,{method:"PUT",headers:this.shopHeaders(),body:JSON.stringify({product:{id:Number(product.externalId),title:product.name,body_html:product.description,tags:product.tags.join(",")}})});return {externalId:String(raw?.product?.id??product.externalId),raw};}
 override async listOrders(store:Store){const d=await request(`${store.baseUrl.replace(/\/$/,"")}/orders.json?status=any&limit=250`,{headers:this.shopHeaders()});return (d.orders??[]).map((o:any)=>({id:String(o.id),storeId:store.id,externalId:String(o.id),status:o.cancelled_at?"cancelled":o.fulfillment_status?"shipped":o.financial_status==="paid"?"paid":"pending",total:Number(o.total_price??0),currency:String(o.currency??"USD"),items:(o.line_items??[]).map((i:any)=>({productId:String(i.product_id??i.id),quantity:Number(i.quantity??0),unitPrice:Number(i.price??0)})),createdAt:o.created_at??new Date().toISOString(),updatedAt:o.updated_at??new Date().toISOString()}));}
}
export class WooCommerceConnector extends GenericCommerceConnector{
 override platform="woocommerce";
 private wcUrl(store:Store,path:string){const u=new URL(`${store.baseUrl.replace(/\/$/,"")}/${path}`);const key=localSecret("woocommerce.consumer_key",process.env.LAYANX_WOOCOMMERCE_CONSUMER_KEY),secret=localSecret("woocommerce.consumer_secret",process.env.LAYANX_WOOCOMMERCE_CONSUMER_SECRET);if(!key||!secret)throw new Error("LAYANX_WOOCOMMERCE_CONSUMER_KEY and LAYANX_WOOCOMMERCE_CONSUMER_SECRET are required");u.searchParams.set("consumer_key",key);u.searchParams.set("consumer_secret",secret);return u.toString();}
 override async createProduct(store:Store,product:Product){const raw=await request(this.wcUrl(store,"products"),{method:"POST",body:JSON.stringify({name:product.name,sku:product.sku,description:product.description,regular_price:String(product.price),stock_quantity:product.inventory,manage_stock:true,tags:product.tags.map(name=>({name}))})});return {externalId:raw?.id?String(raw.id):undefined,raw};}
 override async updateProduct(store:Store,product:Product){if(!product.externalId)return this.createProduct(store,product);const raw=await request(this.wcUrl(store,`products/${encodeURIComponent(product.externalId)}`),{method:"PUT",body:JSON.stringify({name:product.name,sku:product.sku,description:product.description,regular_price:String(product.price),stock_quantity:product.inventory,manage_stock:true})});return {externalId:String(raw?.id??product.externalId),raw};}
 override async listOrders(store:Store){const d=await request(this.wcUrl(store,"orders?per_page=100"),{});return (d??[]).map((o:any)=>({id:String(o.id),storeId:store.id,externalId:String(o.id),status:["cancelled","processing","shipped","completed"].includes(o.status)?(o.status==="completed"?"shipped":o.status):"pending",total:Number(o.total??0),currency:String(o.currency??"USD"),items:(o.line_items??[]).map((i:any)=>({productId:String(i.product_id??i.id),quantity:Number(i.quantity??0),unitPrice:Number(i.price??0)})),createdAt:o.date_created??new Date().toISOString(),updatedAt:o.date_modified??new Date().toISOString()}));}
}
export class ConfiguredSocialConnector implements SocialConnector{
 platform:SocialPlatform;
 constructor(platform:SocialPlatform,private readonly token:string,private readonly endpoint:string){this.platform=platform;}
 async publish(account:SocialAccount,item:{title:string;body:string;mediaUrls:string[]}){const headers:Record<string,string>={"content-type":"application/json"};if(this.token)headers.authorization=`Bearer ${this.token}`;headers["X-LayanX-Idempotency-Key"]=`social:${account.id}:${item.title}:${item.body}`;const d=await request(this.endpoint,{method:"POST",headers,body:JSON.stringify({platform:this.platform,account,item})});const externalId=String(d.externalId??d.id??"");if(!externalId)throw new Error(`social_${this.platform}_missing_external_id`);return {externalId,url:d.url};}
}
export function configuredSocialConnector(platform:SocialPlatform){const p=platform.toUpperCase();const token=localSecret(`${platform}.social.token`,process.env[`LAYANX_${p}_SOCIAL_TOKEN`]);const endpoint=process.env[`LAYANX_${p}_SOCIAL_PUBLISH_URL`];if(!endpoint)throw new Error(`LAYANX_${p}_SOCIAL_PUBLISH_URL is required`);return new ConfiguredSocialConnector(platform,token??"",endpoint);}

export class GenericSocialConnector implements SocialConnector{
 platform:SocialPlatform="generic"; constructor(private readonly token=process.env.LAYANX_SOCIAL_TOKEN){}
 async publish(account:SocialAccount,item:{title:string;body:string;mediaUrls:string[]}){const endpoint=process.env.LAYANX_SOCIAL_PUBLISH_URL;if(!endpoint)throw new Error("LAYANX_SOCIAL_PUBLISH_URL is required for generic social publishing");const headers:Record<string,string>={"content-type":"application/json"};if(this.token)headers.authorization=`Bearer ${this.token}`;const d=await request(endpoint,{method:"POST",headers,body:JSON.stringify({account,item})});return {externalId:String(d.externalId??d.id??""),url:d.url};}
}