import {randomUUID} from "node:crypto";
import type {BusinessManager} from "./manager.js";
import type {GrowthAction,GrowthExperiment,GrowthMetric,GrowthSnapshot,GrowthStage} from "./growth-types.js";
import {GrowthStore} from "./growth-store.js";
const now=()=>new Date().toISOString();
export class GrowthEngine{
 constructor(private readonly business:BusinessManager,private readonly store=new GrowthStore(),private readonly generateText?:(input:string)=>Promise<string>){}
 snapshot():GrowthSnapshot{return this.store.snapshot();}
 createExperiment(input:Omit<GrowthExperiment,"id"|"createdAt"|"status"> & {status?:GrowthExperiment["status"]}){
  const b=this.business.snapshot(); if(input.storeId&&!b.stores.some(s=>s.id===input.storeId))throw new Error("store_not_found"); if(input.productId&&!b.products.some(p=>p.id===input.productId))throw new Error("product_not_found");
  const e={...input,id:randomUUID(),createdAt:now(),status:input.status??"planned"} as GrowthExperiment; this.store.mutate(s=>s.experiments.push(e)); return e;
 }
 recordMetric(input:Omit<GrowthMetric,"date"> & {date?:string}){
  if(!this.store.snapshot().experiments.some(e=>e.id===input.experimentId))throw new Error("experiment_not_found");
  const m={...input,date:input.date??now().slice(0,10)} as GrowthMetric; this.store.mutate(s=>{const i=s.metrics.findIndex(x=>x.experimentId===m.experimentId&&x.date===m.date);if(i>=0)s.metrics[i]=m;else s.metrics.push(m)}); return m;
 }
 private totals(metrics:GrowthMetric[]){return metrics.reduce((a,m)=>{for(const k of ["impressions","views","completedViews","shares","saves","profileVisits","productVisits","addToCart","checkouts","purchases","revenue","repeatPurchases"] as const)a[k]+=m[k];return a},{impressions:0,views:0,completedViews:0,shares:0,saves:0,profileVisits:0,productVisits:0,addToCart:0,checkouts:0,purchases:0,revenue:0,repeatPurchases:0});}
 funnel(experimentId?:string){const s=this.store.snapshot(),ms=experimentId?s.metrics.filter(m=>m.experimentId===experimentId):s.metrics,t=this.totals(ms);return {...t,viewRate:t.impressions?t.views/t.impressions:0,completionRate:t.views?t.completedViews/t.views:0,shareRate:t.views?t.shares/t.views:0,saveRate:t.views?t.saves/t.views:0,visitRate:t.views?t.productVisits/t.views:0,cartRate:t.productVisits?t.addToCart/t.productVisits:0,checkoutRate:t.addToCart?t.checkouts/t.addToCart:0,purchaseRate:t.checkouts?t.purchases/t.checkouts:0,repeatRate:t.purchases?t.repeatPurchases/t.purchases:0,revenuePerVisit:t.productVisits?t.revenue/t.productVisits:0};}
 diagnose(experimentId?:string){const f=this.funnel(experimentId);const candidates=[{stage:"attention" as GrowthStage,value:1-f.viewRate,reason:"Low view-through from impressions."},{stage:"attention" as GrowthStage,value:1-f.completionRate,reason:"Low completion of viewed content."},{stage:"intent" as GrowthStage,value:1-f.shareRate-f.saveRate,reason:"Weak save/share signals relative to views."},{stage:"visit" as GrowthStage,value:1-f.visitRate,reason:"Content is not producing enough product visits."},{stage:"cart" as GrowthStage,value:1-f.cartRate,reason:"Product traffic is not becoming carts."},{stage:"checkout" as GrowthStage,value:1-f.checkoutRate,reason:"Carts are not progressing to checkout."},{stage:"purchase" as GrowthStage,value:1-f.purchaseRate,reason:"Checkout traffic is not becoming purchases."},{stage:"repeat" as GrowthStage,value:1-f.repeatRate,reason:"Few purchasers are returning."}];candidates.sort((a,b)=>b.value-a.value);return {funnel:f,primary:candidates[0]??{stage:"attention" as GrowthStage,value:1,reason:"No metrics yet; start with measurable content experiments."}};}
 async planCycle(input:{projectId:string;storeId?:string;productId?:string;channel?:string}){const b=this.business.snapshot(),product=input.productId?b.products.find(p=>p.id===input.productId):b.products.find(p=>input.storeId?p.storeId===input.storeId:true);if(input.productId&&!product)throw new Error("product_not_found");const diagnosis=this.diagnose();let hypothesis="Test a "+diagnosis.primary.stage+" improvement for "+(product?.name??"the store")+" using a measurable organic-content experiment.";let angle=diagnosis.primary.stage==="attention"?"curiosity hook":diagnosis.primary.stage==="visit"?"problem-to-product bridge":diagnosis.primary.stage==="cart"?"clear offer and proof":diagnosis.primary.stage==="purchase"?"trust, delivery and checkout clarity":"education and repeat-use value";if(this.generateText&&product){try{const raw=await this.generateText("Create one concise growth experiment hypothesis for this product. Diagnose stage: "+diagnosis.primary.stage+". Product: "+JSON.stringify({name:product.name,description:product.description,price:product.price,currency:product.currency,tags:product.tags})+". Return JSON with hypothesis,angle,format. Never invent claims.");const p=JSON.parse(raw.replace(/^\\`\\`\\`json\\s*/,"").replace(/\\s*\\`\\`\\`$/,""));if(typeof p.hypothesis==="string")hypothesis=p.hypothesis;if(typeof p.angle==="string")angle=p.angle;}catch{}}
  const e=this.createExperiment({projectId:input.projectId,storeId:input.storeId,productId:input.productId,name:"Organic Growth Test — "+(product?.name??"Store"),hypothesis,channel:input.channel??"organic",format:"short-form-video",angle});const action=this.addAction({experimentId:e.id,priority:"high",stage:diagnosis.primary.stage,action:this.actionFor(diagnosis.primary.stage),reason:diagnosis.primary.reason});return {experiment:e,action,diagnosis};}
 private actionFor(stage:GrowthStage){return ({attention:"Test 3 distinct hooks for the same offer and keep the winner by completion rate.",intent:"Create save/share-worthy educational content tied to a specific customer problem.",visit:"Add a direct product-context bridge and one clear profile/store action.",cart:"Improve the product offer, proof, price framing and delivery information.",checkout:"Reduce checkout friction and make shipping/returns/payment expectations explicit.",purchase:"Strengthen trust signals, product proof, FAQ and checkout clarity.",repeat:"Build post-purchase education, review requests and a relevant reorder/referral path."} as Record<GrowthStage,string>)[stage];}
 addAction(input:Omit<GrowthAction,"id"|"createdAt"|"status">){const a={...input,id:randomUUID(),createdAt:now(),status:"open" as const};this.store.mutate(s=>s.actions.push(a));return a;}
 completeAction(id:string,status:"done"|"dismissed"="done"){if(!this.store.snapshot().actions.some(x=>x.id===id))throw new Error("growth_action_not_found");this.store.mutate(s=>{const x=s.actions.find(y=>y.id===id)!;x.status=status});return this.store.snapshot().actions.find(x=>x.id===id)!;}
 dashboard(){const s=this.store.snapshot();return {experiments:s.experiments.length,runningExperiments:s.experiments.filter(e=>e.status==="running").length,openActions:s.actions.filter(a=>a.status==="open").length,completedExperiments:s.experiments.filter(e=>e.status==="completed").length,diagnosis:this.diagnose(),funnel:this.funnel()};}
}
