import {spawn,execFileSync} from "node:child_process";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {randomUUID} from "node:crypto";
import {readFile,unlink} from "node:fs/promises";
import type {ToolRequest} from "../core/types.js";
import type {ToolAdapter} from "./executor.js";

type Runner=(command:string,args:string[],timeout?:number)=>Promise<{stdout:string;stderr:string;code:number|null}>;
const MAX_TEXT=4000,MAX_SCREENSHOT_BYTES=5*1024*1024;
const KEYS=new Set(["ENTER","TAB","ESC","ESCAPE","BACKSPACE","DELETE","SPACE","UP","DOWN","LEFT","RIGHT","HOME","END","PAGEUP","PAGEDOWN","SHIFT","CTRL","ALT","META","WIN","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12"]);
function payload(r:ToolRequest){return r.payload&&typeof r.payload==="object"&&!Array.isArray(r.payload)?r.payload as Record<string,unknown>:{};}
function numberValue(v:unknown,n:string,max:number){if(typeof v!=="number"||!Number.isInteger(v)||v<0||v>max)throw new Error(n+" must be an integer between 0 and "+max+".");return v;}
function textValue(v:unknown){if(typeof v!=="string"||!v||v.length>MAX_TEXT)throw new Error("text must be a non-empty string of at most "+MAX_TEXT+" characters.");return v;}
function keyValue(v:unknown){if(typeof v!=="string"||!v)throw new Error("key is required.");const k=v.toUpperCase();if(k.length!==1&&!KEYS.has(k))throw new Error("Unsupported keyboard key.");return k;}
function runner():Runner{return (command,args,timeout=10000)=>new Promise(resolve=>{const c=spawn(command,args,{shell:false,windowsHide:true,timeout});let stdout="",stderr="";c.stdout.on("data",x=>{stdout+=String(x).slice(0,65536);});c.stderr.on("data",x=>{stderr+=String(x).slice(0,65536);});c.on("error",e=>resolve({stdout,stderr:String(e),code:null}));c.on("close",code=>resolve({stdout,stderr,code}));});}

const PS=[
'Add-Type -TypeDefinition "',
'using System;using System.Runtime.InteropServices;using System.Drawing;using System.Drawing.Imaging;using System.IO;public static class L { [DllImport("user32.dll")] public static extern bool SetCursorPos(int x,int y); [DllImport("user32.dll")] public static extern void mouse_event(uint f,uint x,uint y,uint d,IntPtr e); [StructLayout(LayoutKind.Sequential)] public struct I{public uint t;public ushort vk,scan;public uint flags,time;public IntPtr extra;} [DllImport("user32.dll")] public static extern uint SendInput(uint n,I[] i,int s); public static void Move(int x,int y){SetCursorPos(x,y);} public static void Click(bool right){uint d=right?8u:2u,u=right?16u:4u;mouse_event(d,0,0,0,IntPtr.Zero);mouse_event(u,0,0,0,IntPtr.Zero);} public static void Key(ushort k){I a=new I();a.t=1;a.vk=k;SendInput(1,new[]{a},Marshal.SizeOf(typeof(I)));a.flags=2;SendInput(1,new[]{a},Marshal.SizeOf(typeof(I)));} public static void Type(string s){foreach(char c in s){I a=new I();a.t=1;a.scan=c;a.flags=4;SendInput(1,new[]{a},Marshal.SizeOf(typeof(I)));a.flags=6;SendInput(1,new[]{a},Marshal.SizeOf(typeof(I)));}} public static string Shot(){var b=System.Windows.Forms.Screen.PrimaryScreen.Bounds;using(var m=new Bitmap(b.Width,b.Height)){using(var g=Graphics.FromImage(m)){g.CopyFromScreen(b.Location,System.Drawing.Point.Empty,b.Size);}using(var s=new MemoryStream()){m.Save(s,ImageFormat.Png);return Convert.ToBase64String(s.ToArray());}}} }"',
' -ReferencedAssemblies System.Windows.Forms,System.Drawing; $a=$args[0]; $x=[L]::new(); switch($a){ "move" {[L]::Move([int]$args[1],[int]$args[2]);"ok"} "click" {[L]::Move([int]$args[1],[int]$args[2]);[L]::Click($args[3] -eq "right");"ok"} "type" {[L]::Type($args[1]);"ok"} "key" {$m=@{ENTER=13;TAB=9;ESC=27;ESCAPE=27;BACKSPACE=8;DELETE=46;SPACE=32;UP=38;DOWN=40;LEFT=37;RIGHT=39;HOME=36;END=35;PAGEUP=33;PAGEDOWN=34;SHIFT=16;CTRL=17;ALT=18;META=91;WIN=91;F1=112;F2=113;F3=114;F4=115;F5=116;F6=117;F7=118;F8=119;F9=120;F10=121;F11=122;F12=123};$k=$args[1];$v=if($k.Length -eq 1){[int][char]$k}else{$m[$k]};[L]::Key([uint16]$v);"ok"} "shot" {[L]::Shot()} }'
].join("");

export function createDesktopControlToolAdapter(options:{runner?:Runner}={}):ToolAdapter{
 const run=options.runner??runner();
 return {async execute(request){
  const x=payload(request);
  if(request.action==="desktop status"){const platform=process.platform;const commands=platform==="win32"?["powershell.exe"]:platform==="darwin"?["osascript","screencapture"]:["xdotool","gnome-screenshot"];const available=commands.filter(c=>{try{execFileSync(platform==="win32"?"where":"which",[c],{stdio:"ignore"});return true;}catch{return false;}});return {platform,ready:platform==="win32"?available.includes("powershell.exe"):available.length>0,available};}
  const px=numberValue(x.x,"x",20000),py=numberValue(x.y,"y",20000);
  if(request.action==="desktop move mouse"||request.action==="desktop click"){const button=x.button==="right"?"right":"left";if(process.platform==="win32"){const r=await run("powershell.exe",["-NoProfile","-NonInteractive","-Command",PS,request.action==="desktop click"?"click":"move",String(px),String(py),button]);if(r.code!==0)throw new Error(r.stderr||"Windows desktop mouse operation failed.");return {x:px,y:py,...(request.action==="desktop click"?{button}:{})};}if(process.platform==="darwin")throw new Error("macOS desktop control requires an accessibility adapter; install it before enabling desktop actions.");const args=request.action==="desktop click"?["mousemove",String(px),String(py),"click",button==="right"?"3":"1"]:["mousemove",String(px),String(py)];const r=await run("xdotool",args);if(r.code!==0)throw new Error(r.stderr||"xdotool is required for Linux desktop control.");return {x:px,y:py,...(request.action==="desktop click"?{button}:{})};}
  if(request.action==="desktop type"){const value=textValue(x.text);if(process.platform==="win32"){const r=await run("powershell.exe",["-NoProfile","-NonInteractive","-Command",PS,"type",value]);if(r.code!==0)throw new Error(r.stderr||"Windows keyboard input failed.");return {characters:value.length};}if(process.platform==="darwin")throw new Error("macOS desktop control requires an accessibility adapter; install it before enabling desktop actions.");const r=await run("xdotool",["type","--delay","0",value],15000);if(r.code!==0)throw new Error(r.stderr||"xdotool is required for Linux keyboard control.");return {characters:value.length};}
  if(request.action==="desktop press key"){const k=keyValue(x.key);if(process.platform==="win32"){const r=await run("powershell.exe",["-NoProfile","-NonInteractive","-Command",PS,"key",k]);if(r.code!==0)throw new Error(r.stderr||"Windows key press failed.");return {key:k};}if(process.platform==="darwin")throw new Error("macOS desktop control requires an accessibility adapter; install it before enabling desktop actions.");const r=await run("xdotool",["key",k.toLowerCase()]);if(r.code!==0)throw new Error(r.stderr||"xdotool is required for Linux keyboard control.");return {key:k};}
  if(request.action==="desktop screenshot"){let data="";if(process.platform==="win32"){const r=await run("powershell.exe",["-NoProfile","-NonInteractive","-Command",PS,"shot"],15000);if(r.code!==0)throw new Error(r.stderr||"Windows screenshot failed.");data=r.stdout.trim();}else{if(process.platform==="darwin")throw new Error("macOS screenshot is not enabled by this adapter.");const path=join(tmpdir(),"layanx-"+randomUUID()+".png");const r=await run("gnome-screenshot",["-f",path],15000);if(r.code!==0)throw new Error(r.stderr||"gnome-screenshot is required for Linux screenshots.");const bytes=await readFile(path);await unlink(path).catch(()=>{});if(bytes.length>MAX_SCREENSHOT_BYTES)throw new Error("Screenshot exceeds the 5 MiB limit.");data=bytes.toString("base64");}const bytes=Buffer.from(data,"base64");if(bytes.length>MAX_SCREENSHOT_BYTES)throw new Error("Screenshot exceeds the 5 MiB limit.");return {mimeType:"image/png",base64:data,bytes:bytes.length};}
  throw new Error("Unsupported desktop control action.");
 }};
}